version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: embulk-handson
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  embulk:
    container_name: embulk
    build: . 
    volumes:
      - ./output_file:/embulk/output_file
    tty: true

  golang:
    image: golang:1.16
    volumes:
      - ./golang:/go
    working_dir: /go

volumes:
  pgdata:
