version: '3.8'

services:
  postgres:
    image: postgres:13  # または使用したいPostgreSQLのバージョンに応じて変更してください
    environment:
      POSTGRES_DB: embulk-handson
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
