// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tkanata/embulk-hands-on-postgresql2csv/ent/tea"
)

// TeaCreate is the builder for creating a Tea entity.
type TeaCreate struct {
	config
	mutation *TeaMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TeaCreate) SetName(s string) *TeaCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetColor sets the "color" field.
func (tc *TeaCreate) SetColor(s string) *TeaCreate {
	tc.mutation.SetColor(s)
	return tc
}

// SetID sets the "id" field.
func (tc *TeaCreate) SetID(s string) *TeaCreate {
	tc.mutation.SetID(s)
	return tc
}

// Mutation returns the TeaMutation object of the builder.
func (tc *TeaCreate) Mutation() *TeaMutation {
	return tc.mutation
}

// Save creates the Tea in the database.
func (tc *TeaCreate) Save(ctx context.Context) (*Tea, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TeaCreate) SaveX(ctx context.Context) *Tea {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TeaCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TeaCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TeaCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tea.name"`)}
	}
	if _, ok := tc.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Tea.color"`)}
	}
	if v, ok := tc.mutation.ID(); ok {
		if err := tea.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Tea.id": %w`, err)}
		}
	}
	return nil
}

func (tc *TeaCreate) sqlSave(ctx context.Context) (*Tea, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Tea.ID type: %T", _spec.ID.Value)
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TeaCreate) createSpec() (*Tea, *sqlgraph.CreateSpec) {
	var (
		_node = &Tea{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tea.Table, sqlgraph.NewFieldSpec(tea.FieldID, field.TypeString))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(tea.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Color(); ok {
		_spec.SetField(tea.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	return _node, _spec
}

// TeaCreateBulk is the builder for creating many Tea entities in bulk.
type TeaCreateBulk struct {
	config
	builders []*TeaCreate
}

// Save creates the Tea entities in the database.
func (tcb *TeaCreateBulk) Save(ctx context.Context) ([]*Tea, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tea, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TeaCreateBulk) SaveX(ctx context.Context) []*Tea {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TeaCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TeaCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
