-- Create "teas" table
CREATE TABLE "teas" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(100) NOT NULL, "color" character varying(100) NOT NULL, PRIMARY KEY ("id"));
